name: FTP Deploy

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}       # Your FTP host (e.g., ftpupload.net)
          username: ${{ secrets.FTP_USERNAME }} # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }} # Your FTP password
          server-dir: ${{ secrets.FTP_PATH }}   # Usually /htdocs on InfinityFree
          local-dir: ./                         # The folder/files to upload (./ for all)
